services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: games-frontend
    restart: unless-stopped
    ports:
      - "3001:3000"   # Host 3001 → container 3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: games-backend
    restart: unless-stopped
    ports:
      - "8091:8080"   # Host 8091 → container 8080
    depends_on:
      - mysql
    env_file:
      - ./backend/.env.test
  mysql:
    image: mysql:8.0
    container_name: games-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: games_test
      MYSQL_USER: barry75
      MYSQL_PASSWORD: abc123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

