version: "3.9"

services:
  games-backend-test:
    build: ./backend
    container_name: games-backend-test
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://barryonweb.com:3306/games_test
      SPRING_DATASOURCE_USERNAME: barry75
      SPRING_DATASOURCE_PASSWORD: abc123
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xms256m -Xmx512m"
    restart: unless-stopped

  games-frontend-test:
    build: ./frontend
    container_name: games-frontend-test
    ports:
      - "8087:80"
    restart: unless-stopped
