services:
  games-backend-test:
    build: .
    container_name: games-backend-test
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://barryonweb.com:3306/games_test
      SPRING_DATASOURCE_USERNAME: barry75
      SPRING_DATASOURCE_PASSWORD: abc123
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xms256m -Xmx512m"
      SPRING_SERVER_PORT: 8080
    command: ["java", "-jar", "app.jar", "--server.port=8080"]
    restart: unless-stopped
