spring:
  application:
    name: gamesj
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  graphql:
    path: /graphql
server:
  port: ${SERVER_PORT:8082}
websocket:
  timeout-mins: ${WS_TIMEOUT_MINS:20}
  check-interval-sec: ${WS_CHECK_INTERVAL_SEC:45}
useridle:
  timeout-mins: ${USER_IDLE_TIMEOUT_MINS:10}
  check-interval-sec: ${USER_IDLE_CHECK_INTERVAL_SEC:45}
invitation:
  timeout-sec: ${INVITAION_TIMEOUT_SEC:15}


