name: Deploy Full stack App 

env:
  SSH_PORT: 2026

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backend-build-and-deploy: # ----- backend deployment -----------------------
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Setup Java and Maven
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # Build backend
      - name: Build backend
        run: |
          cd backend
          mvn clean package -DskipTests

      # Setup SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Add server to known_hosts
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p $SSH_PORT barryonweb.com >> ~/.ssh/known_hosts

      # Copy published files to server
      - name: Deploy backend files 
        run: |
          ssh -p $SSH_PORT barry75@barryonweb.com "mkdir -p /var/www/games/backend"
          scp -P $SSH_PORT backend/target/gamesj-0.0.1-SNAPSHOT.jar barry75@barryonweb.com:/var/www/games/backend/
      
      # Copy DB scripts to server
      - name: Copy DB scripts 
        run: |
          ssh -p $SSH_PORT barry75@barryonweb.com "mkdir -p /var/www/games/data"
          scp -P $SSH_PORT -r backend/src/main/resources/*.sql barry75@barryonweb.com:/var/www/games/data/

      # Copy images to server
      - name: Deploy images 
        run: |
          ssh -p $SSH_PORT barry75@barryonweb.com "mkdir -p /var/www/games/backend/images"
          scp -P $SSH_PORT backend/src/main/resources/static/images/* barry75@barryonweb.com:/var/www/games/backend/images/    

      # Deploy Nginx config and reload
      - name: Update Nginx config
        run: |
          ssh -p $SSH_PORT barry75@barryonweb.com "mkdir -p /var/www/games/nginx"
          scp -P $SSH_PORT games-dev.barryonweb.com barry75@barryonweb.com:/var/www/games/nginx/
          ssh -p $SSH_PORT barry75@barryonweb.com "
            sudo cp /var/www/games/nginx/games-dev.barryonweb.com /etc/nginx/sites-available/ &&
            sudo ln -sf /etc/nginx/sites-available/games-dev.barryonweb.com /etc/nginx/sites-enabled/ &&
            sudo nginx -t &&
            sudo systemctl reload nginx"

      # Copy service script and Restart backend via systemd
      - name: Copy backend service file and Restart backend service
        run: |
          scp -P $SSH_PORT backend/gamesj.service barry75@barryonweb.com:/etc/systemd/system/
          ssh -p $SSH_PORT barry75@barryonweb.com "sudo systemctl restart gamesj"

      # See logs after restart
      - name: Show backend logs
        run: |
          ssh -p $SSH_PORT barry75@barryonweb.com "journalctl -u gamesj -n 50 --no-pager"

  frontend-build-and-deploy: # ----- frontend deployment ---------------------
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # GitHub - Install frontend dependencies and build
      - name: Build frontend
        run: |
          cd frontend
          npm install  
          cd panel
          npm install
          npm run build
          cd ../sudoku
          npm install
          npm run build
          cd ../connect4
          npm install
          npm run build

      # Start SSH agent with GitHub secret key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Add server to known_hosts to avoid verification errors
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p $SSH_PORT barryonweb.com >> ~/.ssh/known_hosts
     
      # Transfer frontend from GitHub Repo to Ubuntu server via SCP
      - name: Deploy frontend via SSH to server
        run: |
          scp -r -P $SSH_PORT frontend/panel/dist/* barry75@barryonweb.com:/var/www/games/frontend/panel/
          scp -r -P $SSH_PORT frontend/sudoku/dist/* barry75@barryonweb.com:/var/www/games/frontend/sudoku/
          scp -r -P $SSH_PORT frontend/connect4/dist/* barry75@barryonweb.com:/var/www/games/frontend/connect4/


 

 